# start with slim version
FROM python:3.7-slim
MAINTAINER Riverbed Technology

RUN set -ex \
        && install=' \
                git \
                less \
                vim \
        ' \
        && apt-get update && apt-get install -y $install --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN set -ex \
        && buildDeps=' \
                g++ \
                libssl-dev \
                libffi-dev \
        ' \
        && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
        \
        && pip install --src /src \
            -e git+https://github.com/riverbed/steelscript#egg=steelscript \
            -e git+https://github.com/riverbed/steelscript-netprofiler#egg=steelscript-netprofiler \
            -e git+https://github.com/riverbed/steelscript-netshark#egg=steelscript-netshark \
            -e git+https://github.com/riverbed/steelscript-wireshark#egg=steelscript-wireshark \
            -e git+https://github.com/riverbed/steelscript-cmdline#egg=steelscript-cmdline \
            -e git+https://github.com/riverbed/steelscript-scc#egg=steelscript-scc \
            -e git+https://github.com/riverbed/steelscript-appresponse#egg=steelscript-appresponse \
        && pip install --src /src \
            -e git+https://github.com/riverbed/steelscript-steelhead#egg=steelscript-steelhead \
            -e git+https://github.com/riverbed/steelscript-packets.git@master#egg=steelscript-packets \
        && rm -f /src/pip-delete-this-directory.txt \
        && apt-get purge -y --auto-remove $buildDeps \
        && rm -rf ~/.cache
